set(LLVM10_ROOT ${CMAKE_CURRENT_SOURCE_DIR}/llvm10)
set(LLVM10_INCLUDE_DIRS ${LLVM10_ROOT}/include)
set(LLVM10_LIB_DIR ${LLVM10_ROOT}/lib)

find_library(LIBLLVM10_CORE_LIBRARY NAMES LLVMCore HINTS ${LLVM10_LIB_DIR})
find_library(LIBLLVM10_SUPPORT_LIBRARY NAMES LLVMSupport HINTS ${LLVM10_LIB_DIR})
find_library(LIBLLVM10_ANALYSIS_LIBRARY NAMES LLVMAnalysis HINTS ${LLVM10_LIB_DIR})
find_library(LIBLLVM10_BITREADER_LIBRARY NAMES LLVMBitReader HINTS ${LLVM10_LIB_DIR})
find_library(LIBLLVM10_ASMPARSER_LIBRARY NAMES LLVMAsmParser HINTS ${LLVM10_LIB_DIR})

include(FindPackageHandleStandardArgs)
find_package_handle_standard_Args(LLVMV10 DEFAULT_MSG
        LIBLLVM10_CORE_LIBRARY LLVM10_INCLUDE_DIRS)

mark_as_advanced(LLVM10_INCLUDE_DIRS)

add_library(llvm10::core INTERFACE IMPORTED)
set_property(TARGET llvm10::core PROPERTY INTERFACE_LINK_LIBRARIES ${LIBLLVM10_CORE_LIBRARY})
add_library(llvm10::support INTERFACE IMPORTED)
set_property(TARGET llvm10::support PROPERTY INTERFACE_LINK_LIBRARIES ${LIBLLVM10_SUPPORT_LIBRARY})
add_library(llvm10::analysis INTERFACE IMPORTED)
set_property(TARGET llvm10::analysis PROPERTY INTERFACE_LINK_LIBRARIES ${LIBLLVM10_ANALYSIS_LIBRARY})
add_library(llvm10::bitcode INTERFACE IMPORTED)
set_property(TARGET llvm10::bitcode PROPERTY INTERFACE_LINK_LIBRARIES ${LIBLLVM10_BITREADER_LIBRARY} ${LIBLLVM10_ASMPARSER_LIBRARY})

