set(LLVM_ROOT ${CMAKE_SOURCE_DIR}/llvm)
set(LLVM_INCLUDE_DIRS ${LLVM_ROOT}/include)
set(LLVM_LIB_DIR ${LLVM_ROOT}/lib)

find_library(LIBLLVM_CORE_LIBRARY NAMES LLVMCore HINTS ${LLVM_LIB_DIR})
find_library(LIBLLVM_SUPPORT_LIBRARY NAMES LLVMSupport HINTS ${LLVM_LIB_DIR})

include(FindPackageHandleStandardArgs)
find_package_handle_standard_Args(LLVM DEFAULT_MSG
        LIBLLVM_CORE_LIBRARY LLVM_INCLUDE_DIRS)

mark_as_advanced(LLVM_INCLUDE_DIRS)

add_library(llvm::core INTERFACE IMPORTED)
set_property(TARGET llvm::core PROPERTY INTERFACE_LINK_LIBRARIES ${LIBLLVM_CORE_LIBRARY})

add_library(llvm::support INTERFACE IMPORTED)
set_property(TARGET llvm::support PROPERTY INTERFACE_LINK_LIBRARIES ${LIBLLVM_SUPPORT_LIBRARY})

add_library(llvm::analysis INTERFACE IMPORTED)
set_property(TARGET llvm::analysis PROPERTY INTERFACE_LINK_LIBRARIES ${LIBLLVM_SUPPORT_LIBRARY})
