set(LLVM3_ROOT ${CMAKE_SOURCE_DIR}/llvm3)
set(LLVM3_INCLUDE_DIRS ${LLVM3_ROOT}/include)
set(LLVM3_LIB_DIR ${LLVM3_ROOT}/lib)

find_library(LIBLLVM_CORE_LIBRARY NAMES LLVMCore HINTS ${LLVM3_LIB_DIR})
find_library(LIBLLVM_SUPPORT_LIBRARY NAMES LLVMSupport HINTS ${LLVM3_LIB_DIR})
find_library(LIBLLVM_ANALYSIS_LIBRARY NAMES LLVMAnalysis HINTS ${LLVM3_LIB_DIR})
find_library(LIBLLVM_BITREADER_LIBRARY NAMES LLVMBitReader HINTS ${LLVM3_LIB_DIR})
find_library(LIBLLVM_ASMPARSER_LIBRARY NAMES LLVMAsmParser HINTS ${LLVM3_LIB_DIR})

include(FindPackageHandleStandardArgs)
find_package_handle_standard_Args(LLVMV3 DEFAULT_MSG
        LIBLLVM_CORE_LIBRARY LLVM3_INCLUDE_DIRS)

mark_as_advanced(LLVM3_INCLUDE_DIRS)

add_library(llvm3::core INTERFACE IMPORTED)
set_property(TARGET llvm3::core PROPERTY INTERFACE_LINK_LIBRARIES ${LIBLLVM_CORE_LIBRARY})
add_library(llvm3::support INTERFACE IMPORTED)
set_property(TARGET llvm3::support PROPERTY INTERFACE_LINK_LIBRARIES ${LIBLLVM_SUPPORT_LIBRARY})
add_library(llvm3::analysis INTERFACE IMPORTED)
set_property(TARGET llvm3::analysis PROPERTY INTERFACE_LINK_LIBRARIES ${LIBLLVM_ANALYSIS_LIBRARY})
add_library(llvm3::bitcode INTERFACE IMPORTED)
set_property(TARGET llvm3::bitcode PROPERTY INTERFACE_LINK_LIBRARIES ${LIBLLVM_BITREADER_LIBRARY} ${LIBLLVM_ASMPARSER_LIBRARY})

