set(LLVM10_ROOT ${CMAKE_CURRENT_SOURCE_DIR}/llvm10)
set(LLVM10_INCLUDE_DIRS ${LLVM10_ROOT}/include)
set(LLVM10_LIB_DIR ${LLVM10_ROOT}/lib)
set(LLVM10_CONFIG ${LLVM10_ROOT}/bin/llvm-config)

execute_process(COMMAND ${LLVM10_CONFIG} --libfiles OUTPUT_VARIABLE LLVM10_LIB_NAME_STR OUTPUT_STRIP_TRAILING_WHITESPACE)
string(REPLACE " " ";" LLVM10_LIB_NAMEs ${LLVM10_LIB_NAME_STR})

find_library(LIBLLVM10_CORE_LIBRARY NAMES LLVMCore HINTS ${LLVM10_LIB_DIR})
find_library(LIBLLVM10_SUPPORT_LIBRARY NAMES LLVMSupport HINTS ${LLVM10_LIB_DIR})
find_library(LIBLLVM10_ANALYSIS_LIBRARY NAMES LLVMAnalysis HINTS ${LLVM10_LIB_DIR})
find_library(LIBLLVM10_BITREADER_LIBRARY NAMES LLVMBitReader HINTS ${LLVM10_LIB_DIR})
find_library(LIBLLVM10_ASMPARSER_LIBRARY NAMES LLVMAsmParser HINTS ${LLVM10_LIB_DIR})

include(FindPackageHandleStandardArgs)
find_package_handle_standard_Args(LLVMV10 DEFAULT_MSG
        LIBLLVM10_CORE_LIBRARY LLVM10_INCLUDE_DIRS)

mark_as_advanced(LLVM10_INCLUDE_DIRS)

add_library(llvm10::core INTERFACE IMPORTED)
set_property(TARGET llvm10::core PROPERTY INTERFACE_LINK_LIBRARIES ${LLVM10_LIB_NAMEs} -lrt -ldl -ltinfo -lpthread -lm)
